import { t as __exportAll } from "./rolldown-runtime_D7D4PA-g.mjs";
import { g as SITE_TAB, l as SITE_DESCRIPTION, p as SITE_LANGUAGE, t as getCollection, v as SITE_TITLE } from "./_astro_content_0m825bVV.mjs";
import rss from "@astrojs/rss";
import { marked } from "marked";
//#region src/pages/rss.xml.ts
var rss_xml_exports = /* @__PURE__ */ __exportAll({ GET: () => GET });
async function GET(context) {
	const sortedPosts = (await getCollection("blog")).filter((post) => !post.data.draft).sort((a, b) => new Date(b.data.pubDate).getTime() - new Date(a.data.pubDate).getTime());
	function replacePath(content, siteUrl) {
		return content.replace(/(src|img|r|l)="([^"]+)"/g, (match, attr, src) => {
			if (!src.startsWith("http") && !src.startsWith("//") && !src.startsWith("data:")) return `${attr}="${new URL(src, siteUrl).toString()}"`;
			return match;
		});
	}
	const items = await Promise.all(sortedPosts.map(async (blog) => {
		const { data: { title, description, pubDate }, body, slug } = blog;
		const content = body ? replacePath(await marked(body), context.site) : "No content available.";
		const postURL = new URL(`/blog/${slug}/`, context.site);
		return {
			title,
			description,
			link: postURL.toString(),
			guid: postURL.toString(),
			content: `<blockquote>This rendering was automatically generated by Ryuchan Feed and may have formatting issues. For the best experience, please visit: <a href="${postURL}">${postURL}</a></blockquote> ${content}`,
			customData: `
        <dc:creator><![CDATA[${SITE_TAB}]]></dc:creator>
        <pubDate>${new Date(pubDate).toUTCString()}</pubDate>
      `
		};
	}));
	return rss({
		title: SITE_TITLE,
		description: `${SITE_DESCRIPTION} feedId:172229198194932736+userId:166528077360436224`,
		site: context.site,
		stylesheet: "/rss-style.xsl",
		items,
		customData: `
      <language>${SITE_LANGUAGE}</language>
    `,
		xmlns: {
			dc: "http://purl.org/dc/elements/1.1/",
			content: "http://purl.org/rss/1.0/modules/content/",
			atom: "http://www.w3.org/2005/Atom",
			version: "2.0"
		}
	});
}
//#endregion
//#region \0virtual:astro:page:src/pages/rss.xml@_@ts
var page = () => rss_xml_exports;
//#endregion
export { page };
