import rss from "@astrojs/rss";
import { SITE_DESCRIPTION, SITE_LANGUAGE, SITE_TAB, SITE_TITLE } from "@config";
import { getCollection } from "astro:content";
import { marked } from "marked";

export async function GET(context: any) {
  const allPosts = await getCollection("blog");
  // 生产环境过滤草稿
  const posts = import.meta.env.PROD
    ? allPosts.filter((post) => !post.data.draft)
    : allPosts;

  // 按发布时间倒序
  const sortedPosts = posts.sort(
    (a: any, b: any) =>
      new Date(b.data.pubDate).getTime() - new Date(a.data.pubDate).getTime()
  );

  // 相对图片路径转绝对地址（修复原正则错误）
  function replacePath(content: string, siteUrl: string): string {
    return content.replace(/src="([^"]+)"/g, (match, src) => {
      if (!src.startsWith("http") && !src.startsWith("//") && !src.startsWith("data:")) {
        return `src="${new URL(src, siteUrl).toString()}"`;
      }
      return match;
    });
  }

  const items = await Promise.all(
    sortedPosts.map(async (blog: any) => {
      const { data, body, slug } = blog;
      const { title, description, pubDate } = data;

      // 兜底slug：内置slug不存在则使用文件名
      const fileSlug = blog.id?.split("/").pop()?.replace(/\.md$/i, "") || "";
      const finalSlug = slug || fileSlug || String(new Date(pubDate).getTime());

      // 固定你的路由：/blog/xxx
      const postURL = new URL(`/blog/${finalSlug}/`, context.site);
      const siteUrl = context.site.toString();

      // Markdown转HTML + 图片路径补全
      let htmlContent = body ? await marked(body) : "No content available.";
      htmlContent = replacePath(htmlContent, siteUrl);

      // 北京时间UTC+8修正pubDate（你之前一直需要北京时间修正）
      const pubDateObj = new Date(pubDate);
      const utcDate = new Date(pubDateObj.getTime() - 8 * 60 * 60 * 1000);

      return {
        title,
        description: description || "",
        link: postURL.toString(),
        guid: postURL.toString(),
        content: `<blockquote>This rendering was automatically generated by Ryuchan Feed and may have formatting issues. For the best experience, please visit: <a href="${postURL}">${postURL}</a></blockquote> ${htmlContent}`,
        customData: `
          <dc:creator><![CDATA[${SITE_TAB}]]></dc:creator>
          <pubDate>${utcDate.toUTCString()}</pubDate>
        `,
      };
    })
  );

  return rss({
    title: SITE_TITLE,
    description: `${SITE_DESCRIPTION} feedId:172229198194932736+userId:166528077360436224`,
    site: context.site,
    stylesheet: "/rss-style.xsl",
    items,
    customData: `<language>${SITE_LANGUAGE}</language>`,
    xmlns: {
      dc: "http://purl.org/dc/elements/1.1/",
      content: "http://purl.org/rss/1.0/modules/content/",
      atom: "http://www.w3.org/2005/Atom",
    },
  });
}
